services:
- type: web
  name: random-image
  runtime: node
  repo: https://github.com/APARATHAM/random-image
  plan: free
  region: oregon
  buildCommand: npm i
  startCommand: npm test
  autoDeployTrigger: commit
